# try_throw_catch.cpp
//A sample program showcasing exception try, throw, catch.
//These three can live seperate lives. try and throw can live in a function while catch lives in main()
